steps:
  - name: 'gcr.io/cloud-builders/docker'
    id: Build
    args: ['build', '-t', 'gcr.io/$PROJECT_ID/app:$SHORT_SHA', '.']
  - name: 'gcr.io/cloud-builders/docker'
    id: Push
    args: ['push', 'gcr.io/$PROJECT_ID/app:$SHORT_SHA']
  - name: 'gcr.io/cloud-builders/gcloud'
    id: Deploy
    args:
      [
        'beta',
        'run',
        'deploy',
        'rss-monster',
        '--container-image',
        'gcr.io/$PROJECT_ID/app:$SHORT_SHA',
        '--zone',
        'us-central1',
      ]
images:
  - 'gcr.io/$PROJECT_ID/app:$SHORT_SHA'
