steps:
  - name: 'gcr.io/cloud-builders/docker'
    id: Build
    args: ['build', '-t', 'gcr.io/$PROJECT_ID/app:$SHORT_SHA', '.']
  - name: 'gcr.io/cloud-builders/docker'
    id: Push
    args: ['push', 'gcr.io/$PROJECT_ID/app:$SHORT_SHA']
  - name: 'gcr.io/cloud-builders/gcloud'
    id: Deploy
    args:
      [
        'compute',
        'instances',
        'update-container',
        'app',
        '--container-image',
        'gcr.io/$PROJECT_ID/app:$SHORT_SHA',
        '--zone',
        'us-west1-a',
      ]
images:
  - 'gcr.io/$PROJECT_ID/app:$SHORT_SHA'
